#!/bin/bash
set -e

# OpenShift Compatibility Feature — install script
# Makes a devcontainer image compatible with OpenShift restricted SCC:
#   - SSH server (sshd) on configurable port
#   - /etc/ssh/authorized_keys (root-group writable) instead of ~/.ssh
#   - Host keys generated at build time (regenerated at runtime if needed)
#   - /etc/passwd & /etc/group group-writable for runtime UID fix
#   - /home/vscode group-writable (root group) for random UIDs
#   - Fake sudo wrapper (OpenShift blocks real sudo)
#   - Devsy agent binary pre-install (optional, fallback for OpenShift SCC)
#   - DevPod agent binary pre-install (optional, legacy — kept for rollback)
#   - Entrypoint script installed to /usr/local/bin/entrypoint.sh

SSH_PORT="${SSHPORT:-2222}"
INSTALL_DEVSY_AGENT="${INSTALLDEVSYAGENT:-false}"
INSTALL_DEVPOD_AGENT="${INSTALLDEVPODAGENT:-false}"

echo "openshift-compat: configuring for SSH port ${SSH_PORT}, devsy agent: ${INSTALL_DEVSY_AGENT}, devpod agent: ${INSTALL_DEVPOD_AGENT}"

# --- Install openssh-server ---
if ! command -v sshd &> /dev/null; then
  echo "openshift-compat: installing openssh-server"
  apt-get update -y
  apt-get install -y --no-install-recommends openssh-server
  rm -rf /var/lib/apt/lists/*
fi
mkdir -p /run/sshd

# --- Configure sshd ---
SSHD_CONFIG="/etc/ssh/sshd_config"
# Port (replace commented default or append)
if grep -q "^#Port " "$SSHD_CONFIG" 2>/dev/null; then
  sed -i "s/^#Port .*/Port ${SSH_PORT}/" "$SSHD_CONFIG"
elif grep -q "^Port " "$SSHD_CONFIG" 2>/dev/null; then
  sed -i "s/^Port .*/Port ${SSH_PORT}/" "$SSHD_CONFIG"
else
  echo "Port ${SSH_PORT}" >> "$SSHD_CONFIG"
fi
# Password auth off, pubkey on
sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication no/' "$SSHD_CONFIG" 2>/dev/null || true
sed -i 's/^PasswordAuthentication yes/PasswordAuthentication no/' "$SSHD_CONFIG" 2>/dev/null || true
sed -i 's/^#PubkeyAuthentication yes/PubkeyAuthentication yes/' "$SSHD_CONFIG" 2>/dev/null || true
sed -i 's/^#PermitUserEnvironment no/PermitUserEnvironment yes/' "$SSHD_CONFIG" 2>/dev/null || true
sed -i 's/^UsePAM yes/UsePAM no/' "$SSHD_CONFIG" 2>/dev/null || true
# Allow vscode user login
if ! grep -q "^AllowUsers " "$SSHD_CONFIG" 2>/dev/null; then
  echo "AllowUsers vscode" >> "$SSHD_CONFIG"
fi
# Use /etc/ssh/authorized_keys (writable by root group) instead of ~/.ssh
if ! grep -q "^AuthorizedKeysFile " "$SSHD_CONFIG" 2>/dev/null; then
  echo "AuthorizedKeysFile /etc/ssh/authorized_keys" >> "$SSHD_CONFIG"
fi
# StrictModes off — home dir ownership is fluid under random UIDs
if ! grep -q "^StrictModes " "$SSHD_CONFIG" 2>/dev/null; then
  echo "StrictModes no" >> "$SSHD_CONFIG"
fi

# --- /etc/ssh/authorized_keys (root-group writable) ---
touch /etc/ssh/authorized_keys
chmod 644 /etc/ssh/authorized_keys
chgrp 0 /etc/ssh/authorized_keys
chmod g+w /etc/ssh/authorized_keys

# --- Generate host keys at build time ---
# These will be regenerated at runtime into /tmp/ssh if needed (owned by root,
# not readable by random UIDs). Generating now ensures sshd can start in
# environments where /etc/ssh is writable.
ssh-keygen -A 2>/dev/null || true

# --- Make /etc/passwd and /etc/group group-writable (chmod g=u) ---
# So the runtime entrypoint can rewrite the vscode user's UID/GID for
# OpenShift-assigned random UIDs.
chmod g=u /etc/passwd /etc/group

# --- Make /home/vscode group-writable (root group) ---
chgrp -R 0 /home/vscode 2>/dev/null || true
chmod -R g+rwX /home/vscode 2>/dev/null || true

# --- Ensure nvm-managed Node is on PATH for all shells ---
# The node feature installs via nvm, which only adds to .bashrc.
# Under OpenShift, .bashrc may be inaccessible, so add a profile.d script.
if [ -d /usr/local/share/nvm/versions/node ]; then
  NODE_VER=$(ls /usr/local/share/nvm/versions/node 2>/dev/null | tail -1)
  if [ -n "$NODE_VER" ]; then
    cat > /etc/profile.d/nvm-path.sh << NMVEOF
# Auto-generated by openshift-compat feature
export NVM_DIR="/usr/local/share/nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh"
export PATH="/usr/local/share/nvm/versions/node/${NODE_VER}/bin:\$PATH"
NMVEOF
    chmod 755 /etc/profile.d/nvm-path.sh
    # Also link node/npm/npx to /usr/local/bin for non-login shells
    NODE_BIN="/usr/local/share/nvm/versions/node/${NODE_VER}/bin"
    for bin in node npm npx; do
      [ -f "$NODE_BIN/$bin" ] && ln -sf "$NODE_BIN/$bin" /usr/local/bin/$bin
    done
  fi
fi

# --- Fake sudo wrapper ---
# OpenShift restricted SCC sets "no new privileges" which blocks real sudo.
# Many install scripts check for sudo availability (sudo -nl, sudo -v, etc.)
# and use sudo to run commands. This wrapper handles query flags and passes
# through to the real command.
cat > /usr/local/bin/sudo << 'SUDOEOF'
#!/bin/bash
# Fake sudo for OpenShift restricted SCC compatibility
# Handles query flags that installers use to check sudo availability
if [[ "$1" == "-nl" || "$1" == "-ln" ]]; then
    # sudo -nl / -ln: list privileges non-interactively
    # Return success with no output to indicate we "can" run commands
    exit 0
elif [[ "$1" == "-n" ]]; then
    # sudo -n <command>: non-interactive sudo, just run the command
    shift
    exec "$@"
elif [[ "$1" == "-v" ]]; then
    # sudo -v: validate credentials
    exit 0
elif [[ "$1" == "-l" ]]; then
    # sudo -l: list privileges
    echo "(ALL : ALL) NOPASSWD: ALL"
    exit 0
elif [[ "$1" == "-E" || "$1" == "--preserve-env" ]]; then
    shift
    exec "$@"
elif [[ "$1" == "-u" ]]; then
    # sudo -u <user> <cmd> — just run the command as current user
    shift 2
    exec "$@"
else
    # Strip any other sudo flags and run the command
    while [[ "$1" == -* ]]; do
        shift
    done
    exec "$@"
fi
SUDOEOF
chmod +x /usr/local/bin/sudo

# --- Pre-install Devsy agent binary ---
if [[ "$INSTALL_DEVSY_AGENT" == "true" ]]; then
  echo "openshift-compat: pre-installing Devsy agent binary"
  if ! command -v curl >/dev/null 2>&1; then
    apt-get update -y && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
  fi
  # Select architecture-appropriate release asset (reject unsupported archs)
  DEVSY_ARCH="$(uname -m)"
  case "$DEVSY_ARCH" in
    x86_64) DEVSY_ASSET="devsy-linux-amd64" ;;
    aarch64|arm64) DEVSY_ASSET="devsy-linux-arm64" ;;
    *) echo "openshift-compat: unsupported architecture $DEVSY_ARCH for Devsy agent" >&2; exit 1 ;;
  esac
  DEVSY_URL="https://github.com/devsy-org/devsy/releases/latest/download/${DEVSY_ASSET}"
  # Download once to a temp file; --proto =https blocks HTTP redirect hijacking
  curl -fsSL --proto =https "$DEVSY_URL" -o /tmp/devsy-binary
  # /usr/local/bin — always on PATH, not hidden by PVC home mounts
  install -m 755 /tmp/devsy-binary /usr/local/bin/devsy
  # /home/vscode/.local/bin — home-based PATH (may be hidden by PVC)
  mkdir -p /home/vscode/.local/bin
  install -m 755 /tmp/devsy-binary /home/vscode/.local/bin/devsy
  # /etc/skel/.local/bin — repopulated into home on first PVC boot by entrypoint
  mkdir -p /etc/skel/.local/bin
  install -m 755 /tmp/devsy-binary /etc/skel/.local/bin/devsy
  rm -f /tmp/devsy-binary
  # Group permissions for home directory data dirs, but keep binary non-group-writable
  chgrp -R 0 /home/vscode/.local 2>/dev/null || true
  find /home/vscode/.local -type d -exec chmod g+rwX {} + 2>/dev/null || true
  chmod 755 /home/vscode/.local/bin/devsy 2>/dev/null || true
  echo "openshift-compat: Devsy agent installed to /usr/local/bin/devsy, /home/vscode/.local/bin/devsy, /etc/skel/.local/bin/devsy"
fi

# --- Pre-install DevPod agent binary (legacy, kept for rollback) ---
if [ "$INSTALL_DEVPOD_AGENT" = "true" ]; then
  echo "openshift-compat: pre-installing DevPod agent binary (legacy)"
  if ! command -v curl >/dev/null 2>&1; then
    apt-get update -y && apt-get install -y curl tar && rm -rf /var/lib/apt/lists/*
  fi
  mkdir -p /home/vscode/.local/bin
  DEVPOD_URL="https://github.com/loft-sh/devpod/releases/latest/download/devpod_Linux_x86_64.tar.gz"
  curl -fsSL "$DEVPOD_URL" -o /tmp/devpod.tar.gz
  tar -xzf /tmp/devpod.tar.gz -C /tmp devpod 2>/dev/null || tar -xzf /tmp/devpod.tar.gz -C /tmp 2>/dev/null || true
  if [ -f /tmp/devpod ]; then
    mv /tmp/devpod /home/vscode/.local/bin/devpod
  elif [ -f /tmp/devpod-linux-amd64 ]; then
    mv /tmp/devpod-linux-amd64 /home/vscode/.local/bin/devpod
  fi
  rm -f /tmp/devpod.tar.gz
  chmod 755 /home/vscode/.local/bin/devpod 2>/dev/null || true
  chgrp -R 0 /home/vscode/.local 2>/dev/null || true
  chmod -R g+rwX /home/vscode/.local 2>/dev/null || true
  echo "openshift-compat: DevPod agent installed to /home/vscode/.local/bin/devpod"
fi

# --- Install entrypoint.sh ---
cat > /usr/local/bin/entrypoint.sh << 'ENTRYEOF'
#!/bin/bash
set -e

# OpenShift entrypoint for Devsy/DevPod SSH provider.
# Adjusts the vscode user UID to match the OpenShift-assigned random UID,
# sets up SSH, starts sshd, and keeps the container alive.
# Optionally starts the Paseo daemon if the paseo command is available.

CURRENT_UID=$(id -u)
CURRENT_GID=$(id -g)

echo "entrypoint: running as UID=${CURRENT_UID} GID=${CURRENT_GID}"

# Only adjust if we're not root and not the default vscode user (UID 1000)
if [ "$CURRENT_UID" != "0" ] && [ "$CURRENT_UID" != "1000" ]; then
  # Add the current user to /etc/passwd if not already there
  if ! grep -q ":${CURRENT_UID}:" /etc/passwd 2>/dev/null; then
    echo "openshift:x:${CURRENT_UID}:${CURRENT_GID}:OpenShift User:/home/vscode:/bin/bash" >> /etc/passwd
  fi
  # Add all groups (primary + supplementary) to /etc/group if not already there
  for gid in $(id -G); do
    if ! grep -q ":${gid}:" /etc/group 2>/dev/null; then
      echo "openshift-gid-${gid}:x:${gid}:" >> /etc/group
    fi
  done
  # Rewrite the vscode user's UID/GID so SSH allows login as vscode
  # sed -i doesn't work because it creates a temp file and /etc is not writable.
  # Instead, rewrite the file in-place using awk + redirect.
  awk -F: -v uid="$CURRENT_UID" -v gid="$CURRENT_GID" '
    BEGIN { OFS=":" }
    $1 == "vscode" { $3 = uid; $4 = gid }
    { print }
  ' /etc/passwd > /tmp/passwd.new && cat /tmp/passwd.new > /etc/passwd && rm /tmp/passwd.new

  awk -F: -v gid="$CURRENT_GID" '
    BEGIN { OFS=":" }
    $1 == "vscode" { $3 = gid }
    { print }
  ' /etc/group > /tmp/group.new && cat /tmp/group.new > /etc/group && rm /tmp/group.new

  # Verify the change worked
  if grep -q "^vscode:x:${CURRENT_UID}:" /etc/passwd 2>/dev/null; then
    echo "entrypoint: adjusted vscode user to UID=${CURRENT_UID} GID=${CURRENT_GID}"
  else
    echo "entrypoint: WARNING - could not adjust vscode user"
    echo "entrypoint: vscode passwd entry: $(grep '^vscode:' /etc/passwd 2>/dev/null || echo 'NOT FOUND')"
  fi

  # Fix ownership of /home/vscode so sshd accepts authorized_keys
  # Use group 0 (root) so random UID users in group 0 can access
  # Note: as non-root we can't chgrp, but we CAN chmod if we own the files
  # The build-time chgrp 0 should have set group to 0 already.
  # If files were created by later features as UID 1000:GID 1000, we need
  # to fix them. Since we can't chgrp as non-root, we rely on the build-time
  # setup. But we can try to make the dir accessible.
  chmod g+rwX /home/vscode 2>/dev/null || true
  chmod 2775 /home/vscode 2>/dev/null || true
  # If home is still inaccessible or empty (first boot on PVC), populate from /etc/skel
  if [ ! -r /home/vscode/.bashrc ] 2>/dev/null; then
    echo "entrypoint: /home/vscode empty or inaccessible, populating from /etc/skel"
    cp -r /etc/skel/. /home/vscode/ 2>/dev/null || true
    # Ensure essential config dirs exist
    for d in .config .local/share .local/bin .claude .codex .paseo; do
      mkdir -p "/home/vscode/$d" 2>/dev/null || true
    done
  fi
fi

# Set up SSH authorized_keys from mounted secret
# Use /etc/ssh/authorized_keys (configured via AuthorizedKeysFile in sshd_config)
if [ -f /ssh-keys/authorized_keys ]; then
  cat /ssh-keys/authorized_keys > /etc/ssh/authorized_keys
  echo "entrypoint: SSH authorized_keys installed to /etc/ssh/authorized_keys"
fi

# Generate host keys in /tmp/ssh (writable under OpenShift restricted SCC)
# Pre-generated keys in /etc/ssh are owned by root and not readable by random UIDs
HOST_KEY_DIR="/tmp/ssh"
mkdir -p "$HOST_KEY_DIR"
for keytype in rsa ecdsa ed25519; do
  KEY_FILE="$HOST_KEY_DIR/ssh_host_${keytype}_key"
  if [ ! -f "$KEY_FILE" ]; then
    ssh-keygen -t "$keytype" -f "$KEY_FILE" -N "" 2>/dev/null || true
  fi
done

# --- Fix permissions on root-owned config files from image build ---
chgrp -R 0 /home/vscode/.config/devin 2>/dev/null || true
chmod -R g+rwX /home/vscode/.config/devin 2>/dev/null || true

# --- Set up persistent state symlinks from PVC into home directory ---
LINKS_DIR="/workspace-state/home-links"
if [ -d "$LINKS_DIR" ]; then
  for link in "$LINKS_DIR"/* "$LINKS_DIR"/.local/* "$LINKS_DIR"/.config/*; do
    [ -e "$link" ] || continue
    target=$(readlink -f "$link")
    linkname=$(basename "$link")
    case "$link" in
      */.local/*) dest_dir="/home/vscode/.local" ;;
      */.config/*) dest_dir="/home/vscode/.config" ;;
      *) dest_dir="/home/vscode" ;;
    esac
    mkdir -p "$dest_dir" 2>/dev/null || true
    ln -sf "$target" "$dest_dir/$linkname" 2>/dev/null || true
  done
  echo "entrypoint: persistent state symlinks installed from $LINKS_DIR"
fi

# --- Ensure workspace symlink exists ---
if [ -d /workspace-state/workspace ] && [ ! -e /home/vscode/workspace ]; then
  ln -sf /workspace-state/workspace /home/vscode/workspace 2>/dev/null || true
  echo "entrypoint: created workspace symlink -> /workspace-state/workspace"
fi

# --- Ensure paseo is on PATH (nvm-managed, not in /usr/local/bin) ---
PASEO_BIN=$(find /usr/local/share/nvm/versions/node -name paseo -type f 2>/dev/null | head -1)
if [ -n "$PASEO_BIN" ] && [ ! -f /usr/local/bin/paseo ]; then
  ln -sf "$PASEO_BIN" /usr/local/bin/paseo 2>/dev/null || true
  echo "entrypoint: linked paseo to /usr/local/bin"
fi

# --- Set PASEO_HOME globally so CLI and daemon use the same state ---
# The daemon sets PASEO_HOME=/home/vscode/.paseo, but the CLI (and SSH
# sessions) need it too, otherwise they look in ~/.paseo (empty) and don't
# see the daemon's projects/agents/history.
# Under OpenShift restricted SCC, /etc/profile.d and /etc/environment are
# read-only (random UID), so write to the PVC-backed home directory instead.
set +e
mkdir -p /home/vscode/.config/environment.d 2>/dev/null
echo 'PASEO_HOME=/home/vscode/.paseo' > /home/vscode/.config/environment.d/paseo-home.conf 2>/dev/null
# Also add to .bashrc for interactive shells (idempotent)
if [ -f /home/vscode/.bashrc ]; then
  grep -q 'PASEO_HOME=' /home/vscode/.bashrc 2>/dev/null || \
    echo 'export PASEO_HOME=/home/vscode/.paseo' >> /home/vscode/.bashrc 2>/dev/null
fi
# Try /etc/environment as fallback (works if running as root)
grep -q PASEO_HOME /etc/environment 2>/dev/null || echo 'PASEO_HOME=/home/vscode/.paseo' >> /etc/environment 2>/dev/null
# Force HOME for all processes — OpenShift sets HOME=/ which breaks tools
grep -q '^HOME=' /etc/environment 2>/dev/null || echo 'HOME=/home/vscode' >> /etc/environment 2>/dev/null
set -e
echo "entrypoint: set PASEO_HOME=/home/vscode/.paseo globally"

# --- Start Paseo daemon (only if paseo feature is present) ---
PASEO_PID=""
# Source nvm so paseo is on PATH
if [ -f /etc/profile.d/nvm-path.sh ]; then
  . /etc/profile.d/nvm-path.sh
fi
if command -v paseo &> /dev/null; then
  export PASEO_HOME="/home/vscode/.paseo"
  # Force HOME to /home/vscode — OpenShift sets HOME=/ which breaks tools
  # that write to ~/.local/share (devin logs, etc.) and Paseo terminals.
  export HOME="/home/vscode"
  mkdir -p "$PASEO_HOME" 2>/dev/null || true
  mkdir -p "$HOME/.claude" "$HOME/.codex" "$HOME/.config/opencode" 2>/dev/null || true

  # Patch Paseo's injectConnectionHint to append the default port when the
  # Host header has no port (common behind reverse proxies on standard ports).
  PASEO_WEB_UI_SRC=$(find /usr/local/share/nvm/versions/node -path "*/@getpaseo/server/dist/server/server/web-ui.js" -type f 2>/dev/null | head -1)
  [ -z "$PASEO_WEB_UI_SRC" ] && PASEO_WEB_UI_SRC=$(find /usr/lib/node_modules/@getpaseo -path "*/server/server/web-ui.js" -type f 2>/dev/null | head -1)
  if [ -n "$PASEO_WEB_UI_SRC" ] && [ -f "$PASEO_WEB_UI_SRC" ]; then
    PATCHED="$PASEO_HOME/web-ui-patched.js"
    cp "$PASEO_WEB_UI_SRC" "$PATCHED"
    if ! grep -q "defaultPort" "$PATCHED" 2>/dev/null; then
      sed -i 's/const useTls = req.protocol === "https";/const useTls = req.protocol === "https"; const defaultPort = useTls ? 443 : 80; const hostWithPort = host.includes(":") ? host : host + ":" + defaultPort;/' "$PATCHED"
      sed -i 's/listen: host,/listen: hostWithPort,/' "$PATCHED"
      echo "entrypoint: patched web-ui.js to append default port in connection hint"
    fi
    cat > "$PASEO_HOME/web-ui-loader.mjs" << PATCHEOF
export async function resolve(specifier, context, nextResolve) {
  const result = await nextResolve(specifier, context);
  if (result.url && result.url.includes("server/server/web-ui.js") && result.url.includes("@getpaseo")) {
    return { url: "file://$PATCHED", shortCircuit: true };
  }
  return result;
}
PATCHEOF
    export NODE_OPTIONS="--loader=$PASEO_HOME/web-ui-loader.mjs"
  fi

  # Remove stale Paseo PID file if the process is not running
  PASEO_PID_FILE="$PASEO_HOME/paseo.pid"
  if [ -f "$PASEO_PID_FILE" ]; then
    OLD_PID=$(cat "$PASEO_PID_FILE" 2>/dev/null || true)
    if [ -n "$OLD_PID" ] && ! kill -0 "$OLD_PID" 2>/dev/null; then
      echo "entrypoint: removing stale Paseo PID file (PID $OLD_PID not running)"
      rm -f "$PASEO_PID_FILE"
    fi
  fi

  echo "entrypoint: starting Paseo daemon on 127.0.0.1:6767 (web UI enabled, relay toggleable from UI)"
  PASEO_LISTEN=127.0.0.1:6767 \
  paseo daemon start --foreground --web-ui 2>&1 &
  PASEO_PID=$!
else
  echo "entrypoint: paseo not found, skipping Paseo daemon"
fi

# --- Start SSH server ---
echo "entrypoint: starting SSH server on port ${SSHPORT:-2222}"
/usr/sbin/sshd -D -e \
  -h "$HOST_KEY_DIR/ssh_host_rsa_key" \
  -h "$HOST_KEY_DIR/ssh_host_ecdsa_key" \
  -h "$HOST_KEY_DIR/ssh_host_ed25519_key" 2>&1 &
SSHD_PID=$!

# If arguments were passed, exec into them (the daemons run in background)
if [ $# -gt 0 ]; then
  echo "entrypoint: exec'ing into: $*"
  exec "$@"
fi

# Wait for sshd (and paseo if running) to keep container alive
if [ -n "$PASEO_PID" ]; then
  wait -n "$SSHD_PID" "$PASEO_PID"
else
  wait -n "$SSHD_PID"
fi
ENTRYEOF
chmod +x /usr/local/bin/entrypoint.sh

echo "openshift-compat: installation complete"
